### ISSUE TITLE
Pandora ++ v8.7_v007 

### ISSUE THREAD

**Issue by ghost** [JMccormick264/PPAppsIPARepo#95]
Hey JM, I've been running into issues with Pandora ++ lately. I'm running iOS 10.3.3 and the latest Impactor. But, every time I try to listen to a station I get a notification that the station is not available, It does this for all my stations even new ones I create. Any Ideas? 
Thanks, ~ Ian

**Comment by IanAndersonAdorjanCS** [comment]
EDIT: A simple re-install fixed my issue. but, I still can't figure out how to use Pandolife's download feature on the new UI layout do you know?

**Comment by VinZmax** [comment]
I downloaded the 8.4 version and it plays well, skip functions well, and no commercials. But same here with the download feature. I can't find it and have tried all the controls. 
There is a download button (greyed out a bit), and when I hit it, it tells me that 'due to licensing, the song's download is unavailable.

**Comment by JMccormick264** [comment]
As of now, Pandora has patched the tweak. JulioVerne has not released an update for it yet. If and when he does will I update the IPA.
